name: Deploy to Render

on:
  push:
    branches:
      - main   # change if you deploy from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "requirements.txt not found — skipping install"
          fi

      - name: Run tests (if present)
        run: |
          # Run pytest only if there are tests / pytest config files
          if [ -f pytest.ini ] || [ -f pyproject.toml ] || [ -d tests ] || ls *_test.py 1> /dev/null 2>&1 || ls test_*.py 1> /dev/null 2>&1; then
            echo "Tests detected — running pytest"
            pytest
          else
            echo "No tests found — skipping pytest"
          fi

      - name: Trigger Deploy on Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          echo "Triggering Render deploy for service: $RENDER_SERVICE_ID"

          # Call Render API, save response and HTTP code
          http_code=$(curl -sS -o /tmp/render_resp.json -w "%{http_code}" -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            --data-raw '{}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys)

          echo "Render API HTTP status: $http_code"
          echo "Render API response:"
          cat /tmp/render_resp.json || true
          
          # Fail the job if non-2xx response
          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            echo "Render deploy trigger failed (HTTP $http_code)."
            exit 1
          fi

          echo "Render deploy triggered successfully."
